name: Demo_TableIterator
description: Uses pipeline configurations to iterator over one or more gems for a
  given input Dataframe.
version: 0.0.1
author: nathan@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demotableiterator
  parentArtefactID: nathanprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-07-10 00:53:57'
pipelines:
  pipelines/L0_Ingest_from_Source:
    name: L0_Ingest_from_Source
    description: ''
    author: nathan@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-10 00:53:57'
    datasets:
      inputs:
      - datasets/source_path
      outputs:
      - datasets/target_table
    subgraphs: []
    dependencies: {}
datasets:
  datasets/MetadataTable:
    name: MetadataTable
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-07-10 01:23:26'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-07-10 01:23:26'
  datasets/source_path:
    name: source_path
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-07-10 01:27:06'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: File
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-07-10 01:27:06'
  datasets/target_table:
    name: target_table
    description: ''
    author: nathan@prophecy.io
    createdAt: '2024-07-10 01:28:28'
    mode: batch
    physicalDatasets:
      DatabricksCluster:
        fabricId: 117
        datasetType: Database
        description: ''
        author: nathan@prophecy.io
        createdAt: '2024-07-10 01:28:28'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/salesforce:
      name: salesforce
      category: Source/Target
      subCategory: WebApp
      description: null
      author: nathan@prophecy.io
      mode: batch
      files: []
      gemType: DatasetGem
      dependencies: []
      createdAt: '2024-07-10 01:02:55'
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-10 00:53:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-07-10T00:53:57.091568Z'
  name: plibMaven
  version: 8.0.25
  id: '828461667'
  createdAt: '2024-07-10T00:53:57.091568Z'
  type: plibMaven
  enabled: true
  entity: Project
- modifiedAt: '2024-07-10T00:53:57.091568Z'
  name: plibPypi
  version: 1.9.9
  id: '1049074502'
  createdAt: '2024-07-10T00:53:57.091568Z'
  type: plibPypi
  enabled: true
  entity: Project
projectDependencies:
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-10 00:53:35'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-10 00:53:35'
  '12657':
    projectUID: 12657
    projectName: ProphecyWebAppPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12657.git&subPath=
    version: 0.0.5
    isDefault: false
    author: null
    createdAt: '2024-07-10 01:02:08'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
